### ISSUE TITLE
Update PostgreSQL and Firefox version used at Travis CI

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-functionaltest#863]
## Description
Update PostgreSQL and Firefox version used at Travis CI

Now...
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/cf08fdeb2e10a77295a41e9447325746b89ab5b5/.travis.yml#L7-L8

## Affect versions
- 5.7.0.RELEASE

## Issue links
- #xx

**Comment by btiwahorisu** [comment]
> https://travis-ci.community/t/postgresql-11-2-cannot-connect/2680
https://travis-ci.community/t/postgres-default-port-changed-from-5432-to-5433/7347

From the Travis CI Community, I have confirmed that the default connection port when I upgrade to postgres11 will change from 5432 to 5433.
Therefore, since the port number to connect to is predefined in the application's env file, the port number needs to be rewritten.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/e4244d422ec8b7db245aa9cd9b43bcbae58077a2/terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml#L8

The proposed amendment would be one of the following.
**①Use sed command to rewrite the port number of context.xml.**
**②property in context.xml and reference the port number in the environment variable.**

**Comment by btiwahorisu** [comment]
I will consider the appropriateness of each of the proposed amendments.
① is not a problem because it is not an unreasonable operation because it only reproduces operations such as "rewriting a configuration file to match the environment's settings" with a command.
② is a proposal to refactor a design that does not need to be embedded and rewritten in advance, which is a similarly reasonable modification.

From the above, I believe that both are reasonable amendments and therefore need to be judged from a different perspective.
Therefore, i will consider the impact on the application in each of the proposed amendments.
① has no impact on the application, as it is a fix that can be completed in .travis.yml only.
②, it's not reasonable to fix embedding a property in a single configuration file, so any xml with a port number should need to be fixed as well.And if you include the context.xml.env.ftl below, the configuration file will be output from the ftl file, so you will need to change some of the modifications.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/tree/e4244d422ec8b7db245aa9cd9b43bcbae58077a2/terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML

Since there is no need to refactor the entire configuration file with this fix, I think **the proposed fix ① is appropriate**.

**Comment by btiwahorisu** [comment]
In addition to the port number, the default peer authentication settings prevented me from connecting to postgresql locally.
Determine that the event is the same as the one reported in the following issue, and change the configured auth-method to trust.
https://github.com/travis-ci/travis-ci/issues/9624#issuecomment-389537036

In addition to the above, I also confirmed that the pg_hba.conf settings are different between postgresql 9.4 and postgres 11, so I changed the auth-method to allow connections.
- Commit to output pg_hba.conf  
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/commit/29e9e753087680fdc99b62f42ba97d3609305736
- travis output  
https://travis-ci.org/github/terasolunaorg/terasoluna-gfw-functionaltest/jobs/741810818

``` console
$ sudo cat /etc/postgresql/9.4/main/pg_hba.conf
# Database administrative login by Unix domain socket
local   all             postgres                                trust
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
```

``` console
$ sudo cat /etc/postgresql/11/main/pg_hba.conf
# Database administrative login by Unix domain socket
local   all             postgres                                peer
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```
