### ISSUE TITLE
Reflect:Switch from Java EE to Jakarta EE.

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw-functionaltest#904]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1038

## Description
Switch JavaEE library dependencies to JakartaEE library.
The libraries defined in terasoluna-gfw-functionaltest are as follows.

|Java EE|Jakarta EE|
|-|-|
|javax.annotation:javax.annotation-api:1.3.2|jakarta.annotation:jakarta.annotation-api:1.3.5|

I used to put the version definition of annotationa-api in pom.xml, but since it is already defined in [spring-boot](https://docs.spring.io/spring-boot/docs/2.4.0/reference/html/appendix-dependency-versions.html#dependency-versions), there is no need to define it in terasoluna-gfw-functionaltest.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/8de73fe9a774540230f2aef7ea86f527a00dfb14/pom.xml#L218-L224

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Issue links
> Links to related issues.

- #xx

**Comment by btiwahorisu** [comment]
We have confirmed that Jboss 7.3 fails to deploy when testing with Jakarta Servlet 4.0.
From the similar error, it is assumed that the cause is the version of the webapp module and jsf module built into Jboss.
https://stackoverflow.com/questions/43975532/how-to-update-jsf-2-2-to-jsf-2-3-using-maven-in-a-spring-application

We checked the following source.jar built into jboss and confirmed that the same exception handling is implemented.
https://maven.repository.redhat.com/ga/com/sun/faces/jsf-impl/2.3.9.SP05-redhat-00001/
> if (getFacesConfigXmlVersion(facesContext).equals("2.3") || getWebXmlVersion(facesContext).equals("4.0")) {
    throw new FacesException("Unable to find CDI BeanManager");
}

Therefore, it is necessary to exclude JSF from the subsystem and suppress its functionality.
We need to add some configuration to jboss-deployment-structure.xml, so we will reopen it.

**Comment by yoshikawaa** [comment]
Note:

> @btiwahorisu 
> Therefore, it is necessary to exclude JSF from the subsystem and suppress its functionality.
We need to add some configuration to jboss-deployment-structure.xml, so we will reopen it.

We can expect to avoid the error by taking any of the following measures.

* [Disable the JSF subsystem](https://access.redhat.com/documentation/ja-jp/jboss_enterprise_application_platform/6/html/development_guide/exclude_a_subsystem_from_a_deployment)
* [Avoid version conflict between WEB and JSF by using different JSF implementations](https://access.redhat.com/documentation/ja-jp/red_hat_jboss_enterprise_application_platform/7.1/html/configuration_guide/javaserver_faces_jsf_configuration)

Since the TERASOLUNA architecture does not require JSF, we chose to disable the JSF subsystem as a simpler solution.
