### ISSUE TITLE
CsrfTest#test02_CsrfTokenSendByHead does not work on the Pivotal tc server 3.0(tomcat 8.0.9 mode)

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw-functionaltest#91]
Expected are 200(OK), but actual are 405(Method not allowed).

**[Note]**
Pivotal tc server 3.0(tomcat 7.0.55 mode) are worked.

**Comment by kazuki43zoo** [comment]
@btkodakak 

This issue assign to you. If  occur same problem, please support this issue.

**Comment by making** [comment]
This is because https://bz.apache.org/bugzilla/show_bug.cgi?id=56568

**Comment by btshimizukza** [comment]
@btobaramr @making 

In Tomcat8, JSPs only permit GET POST or HEAD.
In this issue, there are two root cause.

1. In this test application, ajax request (used by `PUT` , `DELETE` or `PATCH`) is forwarding to a JSP file.
 -> I think  [current implementation of controller](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/1.0.x/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/csrf/CsrfController.java#L96-L100)) is bad.

2. If CSRF token error occurred, request is forwarding to the JSP of CSRF error by Spring security.
 -> I think  current setting of spring security is not good.

## Possible Solutions

### Solution for 1
Modify to write a body using `@ResponseBody` (without JSP).
e.g.) `CsrfController`
```java
    @RequestMapping(value = "ajax")
    @ResponseBody
    @ResponseStatus(value = HttpStatus.OK)
    public String headCsrfTokenSend() {
        return "OK";
    }
```

### Solution  for 2
Modify to response the 403 error using `HttpServletResponse#sendError` for ajax request path. (add spring security setting)
e.g.) `spring-security.xml`
```xml
    <!-- Add http setting for ajax request path -->
    <sec:http pattern="/csrf/ajax" auto-config="true"
              use-expressions="true" request-matcher="ant">
        <sec:custom-filter ref="csrfFilterErrorPageNotSet" before="LOGOUT_FILTER" />
    </sec:http>
    <!-- for reference (This settings is already set) -->
    <bean id="csrfFilterErrorPageNotSet" class="org.springframework.security.web.csrf.CsrfFilter">
        <constructor-arg index="0" ref="csrfTokenRepository" />
        <property name="accessDeniedHandler">
            <bean
                class="org.springframework.security.web.access.AccessDeniedHandlerImpl" />
        </property>
    </bean>
```

How everyone think ?

**Comment by btshimizukza** [comment]
I think that adding the `isErrorPage="true"` attribute is not best solution in this case.
